In [1]:
! pip install pyvis

Requirement already satisfied: pyvis in c:\users\user\anaconda3\lib\site-packages (0.3.2)
Requirement already satisfied: ipython>=5.3.0 in c:\users\user\anaconda3\lib\site-packages (from pyvis) (8.30.0)
Requirement already satisfied: jinja2>=2.9.6 in c:\users\user\anaconda3\lib\site-packages (from pyvis) (3.1.6)
Requirement already satisfied: jsonpickle>=1.4.1 in c:\users\user\anaconda3\lib\site-packages (from pyvis) (4.1.1)
Requirement already satisfied: networkx>=1.11 in c:\users\user\anaconda3\lib\site-packages (from pyvis) (3.4.2)
Requirement already satisfied: decorator in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.3.0->pyvis) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.3.0->pyvis) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.3.0->pyvis) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.3.0->pyvis) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.3.0->pyvis) (2.19.1)
Requirement already satisfied: stack-data in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.3.0->pyvis) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.3.0->pyvis) (5.14.3)
Requirement already satisfied: colorama in c:\users\user\anaconda3\lib\site-packages (from ipython>=5.3.0->pyvis) (0.4.6)
Requirement already satisfied: wcwidth in c:\users\user\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=5.3.0->pyvis) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\user\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=5.3.0->pyvis) (0.8.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\user\anaconda3\lib\site-packages (from jinja2>=2.9.6->pyvis) (3.0.2)
Requirement already satisfied: executing in c:\users\user\anaconda3\lib\site-packages (from stack-data->ipython>=5.3.0->pyvis) (0.8.3)
Requirement already satisfied: asttokens in c:\users\user\anaconda3\lib\site-packages (from stack-data->ipython>=5.3.0->pyvis) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\user\anaconda3\lib\site-packages (from stack-data->ipython>=5.3.0->pyvis) (0.2.2)

In [19]:
from pyvis.network import Network

In [20]:
# 공간(도화지) 준비하기
nt = Network(notebook = True)

# node: 동그라미
nt.add_node('가')
nt.add_node('나') 
nt.add_node('다')
# edge: 선
nt.add_edge('가', '나')
nt.add_edge('가', '다')


# html 파일 만들기 --> 쥬피터노트북에서 볼 수 있게
nt.show('./sample.html')

Warning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.
./sample.html

In [21]:
import pandas as pd

df = pd.read_excel('./related_word_파이썬.xlsx')
df

       검색어        연관검색어
0      파이썬        파이썬 뜻
1      파이썬       파이썬 독학
2      파이썬       파이썬 기초
3      파이썬      파이썬 자격증
4      파이썬     파이썬 다운로드
..     ...          ...
68  맥북 파이썬    맥북 파이썬 저장
69  맥북 파이썬    맥북 파이썬 파일
70  맥북 파이썬   맥북 파이썬 에디터
71  맥북 파이썬    맥북 파이썬 코딩
72  맥북 파이썬  맥북 파이썬 다운로드

[73 rows x 2 columns]

In [22]:
i = 1
searching = df.loc[i, '검색어']
related_word = df.loc[i, '연관검색어']
print(searching, related_word)

파이썬 파이썬 독학

In [23]:
df.index

RangeIndex(start=0, stop=73, step=1)

In [18]:
nt = Network(notebook = True)

for i in df.index:
    searching = df.loc[i, '검색어']
    related_word = df.loc[i, '연관검색어']
#     print(searching, related_word)
    nt.add_node(searching)
    nt.add_node(related_word)
    nt.add_edge(searching, related_word)
    
nt.show('./graph.html')

Warning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.
./graph.html

In [24]:
from selenium import webdriver
from bs4 import BeautifulSoup
import time
import pandas as pd

In [26]:
def get_related_word(browser, searching):
    
    # 검색어 입력
    input_word_place = browser.find_elements('css selector', '#query')[0]  
    input_word_place.clear( )
    input_word_place.send_keys(searching)
    time.sleep(1)   # 1초 쉬어줘!!!  

    # 연관검색어 찾아서 출력하기
    soup = BeautifulSoup( browser.page_source, "html.parser")
    tag_list = soup.select('li.item._item')
    results =  [ ]
    for tag in tag_list:
        related_word = tag.select('span.kwd_txt')[0].text
        data = [searching, related_word ]
        if searching != related_word:
            results.append(data)

    return results

In [30]:
target = '썬크림'

# 브라우저 열기
browser = webdriver.Chrome()
browser.get('https:/naver.com')
time.sleep(0.5) # 0.5초만 쉬어줘!!!

related_word_list = get_related_word(browser, target)
results =  [ ]
results = results + related_word_list
# 2차연관검색어 수집하기
for related_word_part in related_word_list:
    related_word = related_word_part[1]
    related_word_list2 = get_related_word(browser, related_word)
    results = results + related_word_list

df = pd.DataFrame(results)
df.columns = ['검색어', '연관검색어']
df.to_excel(f'./related_word_{target}.xlsx', index = False)
df

    검색어    연관검색어
0   썬크림    썬크림추천
1   썬크림   남자 썬크림
2   썬크림   헤라 썬크림
3   썬크림    톤업썬크림
4   썬크림   썬크림 세안
..  ...      ...
85  썬크림   썬크림 세안
86  썬크림    달바썬크림
87  썬크림  썬크림 클렌징
88  썬크림   일본 썬크림
89  썬크림  다이소 썬크림

[90 rows x 2 columns]

In [29]:
nt = Network(notebook = True)

for i in df.index:
    searching = df.loc[i, '검색어']
    related_word = df.loc[i, '연관검색어']
#     print(searching, related_word)
    nt.add_node(searching)
    nt.add_node(related_word)
    nt.add_edge(searching, related_word)
    
nt.show(f'./graph_{searching}.html')

Warning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.
./graph_썬크림.html